// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-AppConsentCMP",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-AppConsentCMP", targets: ["AATKit-AppConsentCMP"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-AppConsentCMP",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATAppConsentAdapter",
                    "AATAppConsent",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-AppConsentCMP"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATAppConsentAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATAppConsentAdapter.zip",
            checksum: "70974c1d023b9116c72454edddb7ee34b9d29f84713118f70dccc3811178e061"
        ),
        .binaryTarget(
            name: "AATAppConsent",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AppConsent.zip",
            checksum: "41cf00985229bb589d11c3b509ff550ab602e45cda1665356f2ed880d1c93921"
        ),
    ]
)
