// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-AppConsentCMP",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-AppConsentCMP", targets: ["AATKit-AppConsentCMP"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-AppConsentCMP",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATAppConsentAdapter",
                    "AATAppConsent",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-AppConsentCMP"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATAppConsentAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATAppConsentAdapter.zip",
            checksum: "0628c1f39d78def2108d8721e4c76ceffb216e6dd32cfc9bf1d09d293c8568fb"
        ),
        .binaryTarget(
            name: "AATAppConsent",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AppConsent.zip",
            checksum: "47f338de67d927fe1d096b13ccd8393689200b598d9da7b4db09d3a4b090bd7c"
        ),
    ]
)
