// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-AppConsentCMP",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-AppConsentCMP", targets: ["AATKit-AppConsentCMP"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-AppConsentCMP",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATAppConsentAdapter",
                    "AATAppConsent",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-AppConsentCMP"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATAppConsentAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATAppConsentAdapter.zip",
            checksum: "2622c5e97e994a4f37a8a49d547319b7275bb952a633c37b15488fd1818e74f4"
        ),
        .binaryTarget(
            name: "AATAppConsent",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AppConsent.zip",
            checksum: "ddc79d90015d165953ce4556bc2e87b345c03b3338328bcde2f86e2140272f9b"
        ),
    ]
)
